/**
 *Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:

 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values
 do not exceed four million, find the sum of the even-valued terms.
 */
public class EvenFibonacciNumbers {
    public static void main(String[] args) {
        double number = 1, lastNumber = 0, sumNum = 0, fibNum=0;

        for (int i = 1; fibNum <=4000000 ; i++) {
            fibNum = number + lastNumber;
            lastNumber = number;
            number = fibNum;
            if((fibNum%2) ==0){
                sumNum+=fibNum;

            }
        }

        System.out.println("The sum of the even Fibonacci Numbers is: " + sumNum );
    }
}
